### ISSUE TITLE
Invalid return of a reticulate object from basiliskRun

### ISSUE THREAD

**Issue by LTLA** [Alanocallaghan/snifter#2]
`fi_tsne.matrix` returns a **reticulate** object in the form of a `openTSNE.tsne.TSNEEmbedding`. This is not safe in the **basilisk** context as `basiliskRun` may (or may not) execute in a separate process; the returned **reticulate** object may subsequently refer to a memory address that does not exist, causing all sorts of problems.

`basiliskRun` return values should be pure R objects. In the context of `fi_tsne.matrix`, compliance with this contract is easy enough; just do the `$fit` call inside `basiliskRun` and return the matrix. However, this has implications for `embed` as it means that you cannot reliably return the **reticulate** object from which to call `$transform`.

The likely solution is to extract everything out of the `TSNEEmbedding` object into pure R versions when returning from `fi_tsne()`, and then re-create the same object in `embed()` in order to perform the transformation.

**Comment by alanocallaghan** [comment]
That's unfortunate, makes sense though

**Comment by alanocallaghan** [comment]
Slightly messy solution because to create an embedding object with co-ordinates you need the affinities, and you can't directly construct a `PerplexityBasedNN` object without the old data. Also not super happy about calling `reticulate:::py_ref_to_r` but I can't quite figure out how to get reticulate to wrap sometimes and coerce others.

**Comment by LTLA** [comment]
I think your solution is fine. You could even have `snifter()` return either:

- The embedding matrix without anything else. For people who "just want a t-SNE" or when memory is tight.
- Return a more complex object with all the necessary bits and pieces to do the projection, including the old data.

And people could set a flag indicating which one they wanted.

As for the embedding dimensions, couldn't you just fish it out of `$base`?

**Comment by alanocallaghan** [comment]
Yeah probably better to include that flag, duplicating the affinities could be messy for large data/low mem.

I don't follow re: embedding dimensions? Those are straightforward to grab from the objects. Problem is the `TSNEEmbedding` constructor also requires a `PerplexityBasedNN` as the `affinities` argument (rather than just a bare `Affinity` object), and the latter constructor requires the original data

**Comment by LTLA** [comment]
I just didn't know why you needed the `reticulate:::py_ref_to_r`.

**Comment by alanocallaghan** [comment]
Bear in mind I have a somewhat questionable understanding of python and even worse of reticulate.

My understanding is whenever a python object is "evaluated" (assignment etc), `py_to_r` is called. The return value from `fit()` is of class `openTSNE.TSNEEmbedding`, and `transform` is a member function of that class.

Thus, to allow `transform`ing from R, I need a reference to an `openTSNE.TSNEEmbedding` object, while to get an embedding matrix out of fit, I need to coerce to matrix. Making a new `openTSNE.TSNEEmbedding` is all well and good, but unless I override `py_to_r.[]`, it'll just get converted to a matrix again. 

There's probably a more elegant way to handle this but generally I just want to retain the py handle for a couple of calls until I choose to relinquish it. I can't see a way to inject that choice into the standard `py_to_r` call that's called implicitly on assignment etc.

btw if you have any other suggestions for this please do let me know, otherwise I'll fire a submission on bioc in the next week or so

**Comment by LTLA** [comment]
`reticulate::import` has a `convert=FALSE` that you can set for exactly this purpose, see "Object conversion" at https://rstudio.github.io/reticulate/articles/calling_python.html.

So, the code inside `.create_tsne` becomes:

```r
            openTSNE <- reticulate::import("openTSNE", convert=FALSE)
            obj <- openTSNE$TSNE(...)
            out <- obj$fit(x)
            list(
                x = reticulate::py_to_r(out),
                affinities = out$affinities$P
            )
```

... which should avoid having to get into the S3 weeds.

Other stylistic notes:

- Call `on.exit(basiliskStop(proc))` immediately after `basiliskStart()` so that the process is shut down no matter whether the function errors out or exits properly. Or, you can use the `env=` arguments in `basiliskRun()` to handle all of this for you automatically if you don't need to re-use the same process later on.
- It is legal to pass in **snifter** functions to `basiliskRun` - the entire **snifter** namespace will be loaded in the separate process, so all symbols are guaranteed to be found. This means that you can just write fully fledged functions with the usual `@importFrom` statements, and then pass them to `basiliskRun`. Should yield code that is nicer to read and easier to debug because you can just call and `debug()` it directly.
- You should settle on one of `snifter()` or `fi_tsne()`.
- I would encourage having the projection code in a separate R file, this will make it easier to navigate.

**Comment by alanocallaghan** [comment]
> reticulate::import has a convert=FALSE

Huh, I spent a not inconsiderable amount of time looking for something like that but evidently passed right over the important part of the vignette.
Cheers
